In [1]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [2]:
import torch
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
print(torch.__version__)

2.6.0+cu124


## Intro to Tensors

###Creating Tesnors

In [4]:
#scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

7

In [7]:
#vector
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [8]:
vector.ndim

1

In [9]:
vector.shape

torch.Size([2])

In [10]:
#MATRIX
matrix=torch.tensor([[7,8],[9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [11]:
matrix.ndim

2

In [12]:
matrix.size()

torch.Size([2, 2])

In [13]:
#TENSOR
TENSOR=torch.tensor([[[1,2,3],
                      [4,5,6],
                      [6,7,8]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [6, 7, 8]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
#Create random tensors
random_tensor = torch.rand(1,12,4)
random_tensor

tensor([[[0.8294, 0.8494, 0.7094, 0.6439],
         [0.2891, 0.4253, 0.7854, 0.7974],
         [0.0828, 0.3348, 0.3948, 0.1917],
         [0.8104, 0.3383, 0.3137, 0.4477],
         [0.4425, 0.9736, 0.8437, 0.3753],
         [0.6633, 0.4252, 0.4049, 0.0490],
         [0.0778, 0.3210, 0.2069, 0.3708],
         [0.6006, 0.8424, 0.0322, 0.8723],
         [0.9682, 0.6448, 0.0540, 0.7670],
         [0.5970, 0.0589, 0.8453, 0.2216],
         [0.8861, 0.5717, 0.5474, 0.3088],
         [0.1580, 0.4866, 0.6782, 0.8776]]])

In [17]:
random_tensor.ndim

3

In [18]:
random_image_size_tensor = torch.rand(size=(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [19]:
zeros = torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

  ### Creating a range of tensors and tensors-like

In [20]:
#use torch.range()
z2t=torch.arange(0,100,10)
z2t

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [21]:
#create tensor like
tenzeros=torch.zeros_like(input=z2t)
tenzeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

Tensor datatypes are one of the big issues in pytorch &deep learning: (attributes)
1. Tensor not right datatype(one is float32 and one float16)
2. tensor not right shape
3. tensor not on right device(one is using cuda and one using tpu)

In [22]:
#float 32 tensor
float32tensor = torch.tensor([3.0,4.0,9.0],
                             dtype=torch.float16, #what datatype tensor is
                             device='cpu', #what device is tensor on
                             requires_grad=False #whether or not to track gradients with this tensors operations
                             )
float32tensor


tensor([3., 4., 9.], dtype=torch.float16)

In [23]:
float32tensor.dtype

torch.float16

In [24]:
float16tensor=float32tensor.type(torch.float16)
float16tensor.dtype

torch.float16

In [25]:
float16tensor*float32tensor

tensor([ 9., 16., 81.], dtype=torch.float16)

In [26]:
sometensor=torch.rand(3,4)
sometensor

tensor([[0.5183, 0.6085, 0.5671, 0.6511],
        [0.2731, 0.4603, 0.1492, 0.0328],
        [0.6329, 0.5523, 0.8935, 0.3897]])

In [27]:
sometensor.dtype,sometensor.shape,sometensor.device

(torch.float32, torch.Size([3, 4]), device(type='cpu'))

### Manupulating Tensors(tensor operations)

* Addition
* Subtraction
* Multiplication
* Division
* Matrix Multiplication

In [28]:
tensor = torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [29]:
tensor*10

tensor([10, 20, 30])

In [30]:
tensor-10

tensor([-9, -8, -7])

In [31]:
torch.mul(tensor,10)

tensor([10, 20, 30])

from os import WIFSTOPPED
### Matrix Multiplication

1. Element Wise
2. Matrix Multiplication(Dot Product)

In [32]:
#element wise
tensor*tensor

tensor([1, 4, 9])

In [33]:
#matrix Multiplication
torch.matmul(tensor,tensor)

tensor(14)

In [34]:
a=torch.rand(2,3)
a

tensor([[0.5450, 0.4677, 0.0084],
        [0.7336, 0.4578, 0.4683]])

In [35]:
b=torch.rand(3,6)
b

tensor([[0.8375, 0.3181, 0.2003, 0.7200, 0.1098, 0.8444],
        [0.2300, 0.4583, 0.9504, 0.6992, 0.3635, 0.0174],
        [0.3802, 0.2775, 0.5031, 0.7605, 0.9903, 0.6573]])

In [36]:
torch.matmul(a,b)

tensor([[0.5672, 0.3900, 0.5579, 0.7258, 0.2382, 0.4738],
        [0.8977, 0.5731, 0.8176, 1.2045, 0.7107, 0.9352]])

## Finding Min,Max,Mean,Sum (Tensor Aggregation)

In [37]:
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [38]:
torch.min(x)

tensor(0)

In [39]:
torch.max(x)

tensor(90)

In [40]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [41]:
x.type(torch.float32).mean()

tensor(45.)

In [42]:
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## finding positional min and max

In [43]:
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [44]:
x.argmin() #find the position that has the minimum value with argmin

tensor(0)

In [45]:
x.argmax()

tensor(9)

## Reshaping, Stacking, Squeezing and Unsqueezin Tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of input tensor of certain shape but keep the same memory as original tensor
* Stacking  - Combining multiple tensors on top of each other or side by strided
* Squeeze - removes all `1` dimensions from tensor
* Unsqueese - add a `1` dimension to a target tensor
* Permute - Rwturn a view of the input with dimensions permuted(swapped) in a certain way

In [46]:
import torch
x=torch.arange(1,10)
x,x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [47]:
#add an extra dim
x_reshaped = x.reshape(1,9)
x_reshaped, x_reshaped.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [48]:
#Change the view
z=x.view(1,9)
z,z.shape

(tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]]), torch.Size([1, 9]))

In [49]:
#changing z changes x because view of tensor shares the same memory as originaly
z[:,0]=5
z,x

(tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]]), tensor([5, 2, 3, 4, 5, 6, 7, 8, 9]))

In [50]:
#stack tensors
x_stacked = torch.stack([x,x,x,x],dim=1)
x_stacked

tensor([[5, 5, 5, 5],
        [2, 2, 2, 2],
        [3, 3, 3, 3],
        [4, 4, 4, 4],
        [5, 5, 5, 5],
        [6, 6, 6, 6],
        [7, 7, 7, 7],
        [8, 8, 8, 8],
        [9, 9, 9, 9]])

In [51]:
#squeeze
x_reshaped

tensor([[5, 2, 3, 4, 5, 6, 7, 8, 9]])

In [52]:
x_reshaped.shape

torch.Size([1, 9])

In [53]:
x_squeezed=x_reshaped.squeeze()
x_squeezed

tensor([5, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
x_reshaped.squeeze().shape, x_reshaped.shape

(torch.Size([9]), torch.Size([1, 9]))

In [55]:
x_unsqueezed=x_squeezed.unsqueeze(dim=1)
x_unsqueezed

tensor([[5],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])

In [56]:
#permute
a=torch.rand(2,3,5)
a,a.shape

(tensor([[[0.1060, 0.7983, 0.3705, 0.1185, 0.2201],
          [0.0491, 0.2347, 0.2226, 0.4027, 0.7983],
          [0.5892, 0.2842, 0.7106, 0.3568, 0.2232]],
 
         [[0.3938, 0.5939, 0.9629, 0.5619, 0.0816],
          [0.7468, 0.9150, 0.0793, 0.4973, 0.2542],
          [0.7655, 0.6655, 0.1661, 0.8065, 0.0366]]]),
 torch.Size([2, 3, 5]))

In [57]:
torch.permute(a,(2,0,1)), torch.permute(a,(2,0,1)).shape

(tensor([[[0.1060, 0.0491, 0.5892],
          [0.3938, 0.7468, 0.7655]],
 
         [[0.7983, 0.2347, 0.2842],
          [0.5939, 0.9150, 0.6655]],
 
         [[0.3705, 0.2226, 0.7106],
          [0.9629, 0.0793, 0.1661]],
 
         [[0.1185, 0.4027, 0.3568],
          [0.5619, 0.4973, 0.8065]],
 
         [[0.2201, 0.7983, 0.2232],
          [0.0816, 0.2542, 0.0366]]]),
 torch.Size([5, 2, 3]))

## Indexing (selecting data from tensors)

In [58]:
x=torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [59]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [60]:
x[0][2]

tensor([7, 8, 9])

In [61]:
x[0][1][0]

tensor(4)

## PyTorch tensors and Numpy

* Data in Numpy, in pytorch tensor -> `torch.from_numpy(ndarray)`
* Pytorch to numpy `torch.Tensor.numpy()`

In [62]:
import numpy as np
array=np.arange(1.0,8.0)
tensor=torch.from_numpy(array)
tensor,array

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64),
 array([1., 2., 3., 4., 5., 6., 7.]))

In [63]:
array=array+3
array,tensor

(array([ 4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [64]:
tensor=torch.rand(7)
tensor

tensor([0.2789, 0.6145, 0.8041, 0.3261, 0.1006, 0.3564, 0.4373])

In [65]:
numpytensor=tensor.numpy()
numpytensor,numpytensor.dtype

(array([0.27891546, 0.6144881 , 0.8040903 , 0.3261208 , 0.10055035,
        0.35636467, 0.4373173 ], dtype=float32),
 dtype('float32'))

In [66]:
tensor=tensor+1
tensor,numpytensor

(tensor([1.2789, 1.6145, 1.8041, 1.3261, 1.1006, 1.3564, 1.4373]),
 array([0.27891546, 0.6144881 , 0.8040903 , 0.3261208 , 0.10055035,
        0.35636467, 0.4373173 ], dtype=float32))

## Reproducibility(trying to take random out of random)

to reduce the randomness in nn and pytorch **random seed** comes in


In [67]:
randomA=torch.rand(3,4)
randomB=torch.rand(3,4)

randomA,randomB,randomA==randomB

(tensor([[0.4641, 0.5557, 0.9731, 0.6439],
         [0.9449, 0.9789, 0.2647, 0.9823],
         [0.2421, 0.3396, 0.2145, 0.8994]]),
 tensor([[0.5139, 0.1699, 0.1169, 0.6200],
         [0.5176, 0.2502, 0.2098, 0.3010],
         [0.7813, 0.7274, 0.6453, 0.3095]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [68]:
#Random reproducable tensors
RANDOM_SEED=42
torch.manual_seed(RANDOM_SEED)

randomC=torch.rand(3,4)
torch.manual_seed(RANDOM_SEED)
randomD=torch.rand(3,4)

randomC,randomD,randomC==randomD

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))

## Running tensors in GPU

faster computation

### 1. Getting a GPU

1. Use Google Colab
2. Own GPU
3. Colab Computing GCP,AWS

In [69]:
!nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


### 2. Check for GPU access with pytorch

In [70]:
import torch
torch.cuda.is_available()

False

In [71]:
#setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'

In [72]:
torch.cuda.device_count()

0

### 3. Putting tensors(and models) on GPU

The reason we want our tensors/models on GPU is because GPU results in fast computation

In [73]:
tensor=torch.tensor([1,2,3])
tensor,tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [74]:
#move to gpu if available
tensorongpu=tensor.to(device)
tensorongpu

tensor([1, 2, 3])

###4. Moving back to cpu

In [75]:
#tensor on gpu can't transform it to NumPy
# tensorongpu.numpy()

In [76]:
#to fix first set on cpu
tensoroncpu=tensorongpu.cpu().numpy()
tensoroncpu


array([1, 2, 3])